---
- name: Download RHEL Virtualization Images
  hosts: localhost
  gather_facts: true
  vars_files:
    - main.yml

  tasks:
    - name: Download RHEL images
      ansible.builtin.include_role:
        name: rhel_download
      vars:
        rhel_download_image_version: "{{ rhel_version }}"
      loop: "{{ rhel_versions }}"
      loop_control:
        loop_var: rhel_version
...

